name: Deploy SVMX to ORG

on:
  push:
    branches:
      - SandBox_Branch
    paths:
      - 'force-app/**'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: AE2
    steps:

      - name: 'Update Latest Node'
        uses: actions/setup-node@v1
        with:
          node-version: '>=14'
          check-latest: true

    # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          
    # Install SVMX CLI
      - name: Install ServiceMax CLI
        run: |
          echo y | sf plugins install svmxc-sf

    # Echo Salesforce confg
      - name: Check Salesforce CLI config
        run: 'sf config list'

    # Store secret for dev hub
      - name: 'Populate auth file with SKF_AE2_AUTHURL secret'
        shell: bash
        run: 'echo ${{ secrets.SKF_AE2_AUTHURL}} > ./SKF_AE2_AUTHURL.txt'

    # Authenticate UAT ORG
      - name: 'Authenticate AE2 ORG'
        run: 'sf org login sfdx-url -f ./SKF_AE2_AUTHURL.txt -a AE2 -d'
 
      # Deploy delta package
      - name: Deploy DIFF package
        run: 'sf svmxc deploy -o skfdevaswin.visveswar@skf.com  -f'
